MovieFlix/Models/Movie.cs
namespace MovieFlix.Models
{
    public class Movie
    {
        public int MovieId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Rating { get; set; }

        public DateTime? ReleaseDate { get; set; } // Make ReleaseDate nullable
        public string ImageUrl { get; set; }

        //cinema items
        public int? CinemaId { get; set; }
        public Cinema Cinema { get; set; }

        // Genre items
        public int GenreId { get; set; }
       
        public Genre Genre { get; set; }
    }

}

MovieFlix/Controllers/AnalyticsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieFlix.Data;
using MovieFlix.Models;
using MovieFlix.Models.Dtos;
using MovieFlix.ViewModels;
using System.Linq;
using System.Threading.Tasks;


[Authorize]
public class AnalyticsController : Controller
{
    private readonly MovieflixContext _context;
    private readonly UserManager<ApplicationUser> _userManager;

    public AnalyticsController(MovieflixContext context, UserManager<ApplicationUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> RecordHover([FromBody] HoverDataDto data)
    {
        var user = await _userManager.GetUserAsync(User);
        var movie = await _context.Movies.FindAsync(data.MovieId);
        if (movie == null) return NotFound();
        if (user == null)
        {
            return Unauthorized(); // or handle as needed
        }

        var analytics = new MovieAnalytics
        {
            MovieId = data.MovieId,
            UserId = user.Id,
            HoverDurationMs = data.HoverDuration,
            CinemaId = movie.CinemaId ?? 0
        };

        _context.MovieAnalytics.Add(analytics);
        await _context.SaveChangesAsync();

        return Ok();
    }
    [Authorize(Roles = "CinemaAdmin,SuperAdmin")]
    public async Task<IActionResult> CinemaAnalytics(int? cinemaId)
    {
        var user = await _userManager.GetUserAsync(User);

        if (User.IsInRole("CinemaAdmin"))
        {
            cinemaId = user?.CinemaId;
        }

        // Get popular movies
        var popularMovies = await _context.MovieAnalytics
       .Where(a => cinemaId == null || a.CinemaId == cinemaId)
       .Join(
           _context.Movies,
           analytics => analytics.MovieId,
           movie => movie.MovieId,
           (analytics, movie) => new { analytics, movie }
       )
       .GroupBy(x => x.movie.Title)
       .Select(g => new MovieHoverData
       {
           MovieTitle = g.Key,
           TotalHoverTime = g.Sum(x => x.analytics.HoverDurationMs)
       })
       .OrderByDescending(x => x.TotalHoverTime)
       .Take(10)
       .ToListAsync();

        var popularGenres = await _context.MovieAnalytics
            .Where(a => cinemaId == null || a.CinemaId == cinemaId)
            .Join(
                _context.Movies.Include(m => m.Genre),
                analytics => analytics.MovieId,
                movie => movie.MovieId,
                (analytics, movie) => new { analytics, movie.Genre.Name }
            )
            .GroupBy(x => x.Name)
            .Select(g => new GenreHoverData
            {
                Genre = g.Key,
                TotalHoverTime = g.Sum(x => x.analytics.HoverDurationMs)
            })
            .OrderByDescending(x => x.TotalHoverTime)
            .ToListAsync();


        var viewModel = new CinemaAnalyticsViewModel
        {
            PopularMovies = popularMovies,
            PopularGenres = popularGenres
        };

        return View(viewModel);
    }

}

MovieFlix/Controllers/AuditLogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;  // for UserManager
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieFlix.Data;
using MovieFlix.Models;  
using MovieFlix.ViewModels;  
using System.Linq;
using System.Threading.Tasks;



[Authorize(Roles = "SuperAdmin")]
public class AuditLogController : Controller
{
    private readonly MovieflixContext _context;
    private readonly UserManager<ApplicationUser> _userManager;

    public AuditLogController(MovieflixContext context, UserManager<ApplicationUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    public IActionResult Index()
    {
        return View();  // View with empty table that DataTables will fill
    }

    [HttpGet]
    public async Task<IActionResult> GetAuditLogs()
    {
        var logs = await _context.AuditLogs
            .OrderByDescending(l => l.Timestamp)
            .Take(100)
            .ToListAsync();

        var data = new List<object>();

        foreach (var log in logs)
        {
            var user = await _userManager.FindByIdAsync(log.UserId);
            data.Add(new
            {
                timestamp = log.Timestamp.ToString("yyyy-MM-dd HH:mm:ss"),
                username = user?.UserName ?? "Unknown",
                action = log.Action,
                entityName = log.EntityName,
                entityId = log.EntityId,
                details = log.Details
            });
        }

        return Json(new { data });
    }
}

MovieFlix/Controllers/GenresController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieFlix.Data;
using MovieFlix.Models;
using MovieFlix.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieFlix.Controllers
{
    public class GenresController : Controller
    {
        private readonly MovieflixContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public GenresController(MovieflixContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            IQueryable<Genre> genresQuery = _context.Genres.Include(g => g.Movies);


            if (User.IsInRole("CinemaAdmin") && currentUser?.CinemaId != null)
            {
             
            }

            var genres = await genresQuery.ToListAsync();


            var viewModelList = genres.Select(g => new GenreViewModel
            {
                GenreId = g.GenreId,
                Name = g.Name,
                MovieCount = User.IsInRole("CinemaAdmin") && currentUser?.CinemaId != null
                    ? g.Movies.Count(m => m.CinemaId == currentUser.CinemaId)
                    : g.Movies.Count
            }).ToList();

            return View(viewModelList);
        }



        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GenreId,Name")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GenreId,Name")] Genre genre)
        {
            if (id != genre.GenreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.GenreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genre = await _context.Genres.FindAsync(id);
            if (genre != null)
            {
                _context.Genres.Remove(genre);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
            return _context.Genres.Any(e => e.GenreId == id);
        }

        [HttpGet]
        public async Task<IActionResult> GetGenres()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            IQueryable<Genre> genresQuery = _context.Genres.Include(g => g.Movies);

            var genres = await genresQuery.ToListAsync();

            var isCinemaAdmin = User.IsInRole("CinemaAdmin");
            var userCinemaId = currentUser?.CinemaId;

            var genreViewModels = genres.Select(g => new GenreViewModel
            {
                GenreId = g.GenreId,
                Name = g.Name,
                // If CinemaAdmin, count movies belonging only to user's CinemaId
                MovieCount = (isCinemaAdmin && userCinemaId != null)
                    ? g.Movies.Count(m => m.CinemaId == userCinemaId)
                    : g.Movies.Count
            }).ToList();

            return Json(new { data = genreViewModels });
        }


    }
}

MovieFlix/Views/Movie/Create.cshtml
@model MovieFlix.ViewModels.MovieFormViewModel

@{
    ViewData["Title"] = "Add New Movie";
}

<div class="container-fluid">

    <h2 class="text-center" style="color:#C3CBFF">@ViewData["Title"]</h2>

    <div class="container">
        <form asp-action="Create" enctype="multipart/form-data" method="post" class="text-white p-4 rounded shadow-lg">

            <div class="row mb-3 fs-5">
                <div class="col-md-6" style="color:#C3CBFF">
                    <label asp-for="Title" class="form-label text-primary"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger small"></span>
                </div>

                <div class="col-md-6" style="color:#C3CBFF">
                    <label asp-for="ReleaseDate" class="form-label text-primary"></label>
                    <input asp-for="ReleaseDate" class="form-control" type="date" />
                    <span asp-validation-for="ReleaseDate" class="text-danger small"></span>
                </div>
            </div>

            <div class="row mb-3 fs-5">
                <div class="col-md-6" style="color:#C3CBFF">
                    <label asp-for="GenreId" class="form-label text-primary"></label>
                    <select asp-for="GenreId" asp-items="Model.Genres" class="form-select">
                        <option value="">-- Select Genre --</option>
                    </select>
                    <span asp-validation-for="GenreId" class="text-danger small"></span>
                </div>

                <div class="col-md-6" style="color:#C3CBFF">
                    <label asp-for="Rating" class="form-label text-primary"></label>
                    <input asp-for="Rating" class="form-control" type="number" step="0.1" />
                    <span asp-validation-for="Rating" class="text-danger small"></span>
                </div>
            </div>

            <div class="row mb-3 fs-5">
                <div class="col-md-6" style="color:#C3CBFF">
                    <label asp-for="CinemaId" class="form-label text-primary"></label>
                    <select asp-for="CinemaId" asp-items="Model.Cinemas" class="form-select">
                        <option value="">-- Select Cinema --</option>
                    </select>
                    <span asp-validation-for="CinemaId" class="text-danger small"></span>
                </div>

                <div class="col-md-6" style="color:#C3CBFF">
                    <label asp-for="ImageFile" class="form-label text-primary fs-5">Upload Movie Poster</label>
                    <input asp-for="ImageFile" type="file" class="form-control" required />
                    <span asp-validation-for="ImageFile" class="text-danger small"></span>
                </div>
            </div>

            <div class="form-group mb-3 fs-5" style="color:#C3CBFF">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Description" class="text-danger small"></span>
            </div>

            <div class="d-flex gap-3 justify-content-center">
                <button type="submit" class="btn btn-success px-4">
                    <i class="bi bi-check-circle me-1"></i> Save
                </button>

                <a asp-action="Index" class="btn btn-danger">
                    <i class="bi bi-x-circle me-1"></i> Cancel
                </a>
            </div>

        </form>
    </div>
</div>

MovieFlix/Views/Movie/Delete.cshtml
@model MovieFlix.Models.Movie
@{
    ViewData["Title"] = "Delete Movie";
}
<div class="container-fluid">
    <h2 class="text-center mb-5" style="color:#C3CBFF">@ViewData["Title"]</h2>

    <div class=" text-white p-4 rounded shadow-lg">
    <dl class="row text-light text-center">
         <dd >
            <img src="@Model.ImageUrl" width="200" />
        </dd>

            <dt class="fs-3" style="color:#C3CBFF">Title</dt>
            <dd class="fs-4" style="color:#C3CBFF">@Model.Title</dd>

            <dt class="fs-3" style="color:#C3CBFF">Genre</dt>
            <dd class="fs-4" style="color:#C3CBFF">@Model.Genre?.Name</dd>

          
    </dl>


    
        <h3 class="text-center" style="color:#C3CBFF">Are you sure you want to delete this?</h3>

    <form asp-action="Delete" class="text-center gap-4">
        <input type="hidden" asp-for="MovieId" />
            <button type="submit" class="btn btn-danger mt-2">
            <i class="bi bi-trash"></i> Delete
            </button>
        <a asp-action="Index" class="btn btn-secondary mt-2">
            <i class="bi bi-x-circle"></i> Cancel
        </a>
    </form>
</div>
</div>

MovieFlix/Views/Movie/Edit.cshtml
@model MovieFlix.ViewModels.MovieFormViewModel

@{
    ViewData["Title"] = "Edit Movie";
}
<div class="container-fluid">
    <h2 class="text-center my-4 " style="color:#C3CBFF">@ViewData["Title"]</h2>

    <div class="container ">
        <form asp-action="Edit" enctype="multipart/form-data" method="post" class=" text-white p-4 rounded shadow-lg">
            <input type="hidden" asp-for="MovieId" />
            <input type="hidden" asp-for="ImageUrl" />

            @if (!string.IsNullOrEmpty(Model.ImageUrl))
            {
                <div class="mb-3 text-center">
                    <label class="form-label fs-5" style="color:#C3CBFF">Current Image:</label><br />
                    <img src="@Model.ImageUrl" alt="Current Movie Image" class="img-thumbnail movie-img" style="width: 200px;" />
                </div>
            }
            <div class="row mb-3 fs-5">
               
                <div class="col-md-6 " style="color:#C3CBFF">
                    <label asp-for="Title" class="form-label text-primary"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger small"></span>
                </div>

                <div class="col-md-6" style="color:#C3CBFF">
                    <label asp-for="ReleaseDate" class="form-label text-primary"></label>
                    <input asp-for="ReleaseDate" class="form-control" type="date" />
                    <span asp-validation-for="ReleaseDate" class="text-danger small"></span>
                </div>
       
            </div>
       
            <div class="row mb-3 fs-5">

                <div class="col-md-6 " style="color:#C3CBFF">
                    <label asp-for="GenreId" class="form-label text-primary"></label>
                    <select asp-for="GenreId" asp-items="Model.Genres" class="form-select">
                        <option value="">-- Select Genre --</option>
                    </select>
                    <span asp-validation-for="GenreId" class="text-danger small"></span>
                </div>


                <div class="col-md-6 " style="color:#C3CBFF">
                    <label asp-for="Rating" class="form-label text-primary"></label>
                    <input asp-for="Rating" class="form-control" type="number" step="0.1" />
                    <span asp-validation-for="Rating" class="text-danger"></span>
                </div>

            </div>

            <div class="row mb-3 fs-5">

                <div class="col-md-6" style="color:#C3CBFF">
                    <label asp-for="CinemaId" class="form-label text-primary"></label>
                    <select asp-for="CinemaId" asp-items="Model.Cinemas" class="form-control"></select>
                    <span asp-validation-for="CinemaId" class="text-danger"></span>
                </div>


                <div class="col-md-6" style="color:#C3CBFF">
                    <label asp-for="ImageFile" class="form-label text-primary fs-5" style="color:#C3CBFF">Replace Image</label>
                    <input asp-for="ImageFile" type="file" class="form-control" />
                    <span asp-validation-for="ImageFile" class="text-danger small"></span>
                </div>
               

            </div>

            <div class="form-group mb-3 fs-5" style="color:#C3CBFF">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="d-flex gap-3 justify-content-center">
                <button type="submit" class="btn btn-success px-4">
                    <i class="bi bi-check-circle me-1"></i> Save  
                </button>
                <a asp-action="Index" class="btn btn-danger">
                    <i class="bi bi-x-circle me-1"></i> Cancel
                </a>
            </div>
        </form>
    </div>
</div>

MovieFlix/Views/Movie/Index.cshtml
@model IEnumerable<MovieFlix.Models.Movie>
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["Title"] = "Movie List";
}
<div class="container-fluid">
    <div>
    <h2 class="text-white mb-4">Movies</h2>

    <p class="gap-4">
        <a asp-action="Create" class="btn btn-outline-info mb-4 ">
            <i class="bi bi-plus-circle me-1"></i> Add New Movie
        </a>  
        <a asp-controller="Genres" asp-action="Index" class="btn btn-outline-warning mb-4">
            <i class="bi bi-collection-play me-1"></i> Manage Genres
        </a>

            @if (SignInManager.IsSignedIn(User) && (User.IsInRole("CinemaAdmin") || User.IsInRole("SuperAdmin")))
            {
                <a asp-controller="Analytics" asp-action="CinemaAnalytics" class="btn btn-outline-info mb-4">
                    <i class="bi bi-journal-text me-1"></i> Analytical report
                </a>
            }
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("SuperAdmin"))
        {
            <a asp-controller="AuditLog" asp-action="Index" class="btn btn-outline-info mb-4">
                <i class="bi bi-journal-text me-1"></i> View  Logs
            </a>

        }
           
    </p>
    </div>

  

            <div class="row g-4 mb-4">
                @foreach (var movie in Model)
                {
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 ">
                        <div class="movie-card">
                            <img src="@movie.ImageUrl" class="card-img-top" alt="@movie.Title" />
                            <div class="card-body d-flex flex-column">
                        <h5 class="card-title fs-5" style="color:#C3CBFF">@movie.Title</h5>
                                <div class="mt-auto d-flex gap-2 ">
                                    <a asp-action="Edit" asp-route-id="@movie.MovieId" class="btn btn-sm btn-outline-warning">
                                        <i class="bi bi-pencil-square"></i>
                                     </a>
                                    <a asp-action="Delete" asp-route-id="@movie.MovieId" class="btn btn-sm btn-outline-danger">
                                        <i class="bi bi-trash"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
        </div>
   </div>